version = 0.1

[default.deploy.parameters]
stack_name = "sentiment-analysis-service"
resolve_s3 = true
s3_prefix = "sentiment-analysis-service"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
